
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      groups:
        - firebase_credentials
        - google_credentials
      android_signing:
        - weathercodemagic
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Decode Google credentials
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Flutter Doctor
        script: |
          flutter doctor -v
      - name: Flutter Clean
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Test All Layers
        script: |
          flutter test --coverage test packages/open_meteo_api/test packages/weather_repository/test
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/**/outputs/**/*.aab
    publishing:

      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:782776044559:android:ccea9ba085ff1892c5e77a
          groups:
            - Ihsane_Tech
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email

      email:
        recipients:
          - moushab17@gmail.com
        notify:
          success: true
          failure: false