
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - weathercodemagic
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Flutter Doctor
        script: |
          flutter doctor -v
      - name: Flutter Clean
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Test All Layers
        script: |
          flutter test --coverage test packages/open_meteo_api/test packages/weather_repository/test
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
      - name: Install fastlane-plugin-firebase_app_distribution
        script: |
          gem install bundler
          sudo gem install fastlane-plugin-firebase_app_distribution --user-install
      - name: Execute fastlane android publishing task
        script: |
          cd android
          bundle install
          bundle exec fastlane <your_android_lane>
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
#      android:
#        app_id: 1:133119966084:android:95595c1ca11c02c57e7bd1
#        groups:
#          - Jamiil_Tech
#        artifact_type: 'apk'
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - moushab17@gmail.com
        notify:
          success: true
          failure: false


 # Replace with 'aab' to only publish the Android app bundle
