
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      groups:
        - firebase_credentials
        #- google_credentials
      android_signing:
        - weathercodemagic
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Flutter Doctor
        script: |
          flutter doctor -v
      - name: Flutter Clean
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Test All Layers
        script: |
          flutter test --coverage test packages/open_meteo_api/test packages/weather_repository/test
      - name: Version Increment
        script: |
          current_version=$(awk '/version:/{print $2}' pubspec.yaml)
          echo "Current version: $current_version"
          major=$(echo $current_version | cut -d. -f1)
          echo "Major: $major"
          minor=$(echo $current_version | cut -d. -f2)
          echo "Minor: $minor"
          patch=$(echo $current_version | cut -d. -f3)
          echo "Patch: $patch"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "Version before increment: $current_version"
          echo "New version: $new_version"
          sed -i '' "s/^version:.*$/version: $new_version/" pubspec.yaml


      - name: Build APK with Flutter
        script: |
          current_version=$(awk '/version:/{print $2}' pubspec.yaml)
          echo "Current version: $current_version"
          flutter build apk --release
        #flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      #google_play:
        #track: internal
        #credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:58082583887:android:00abf24c426e3f18e5113a
          groups:
            - androidTesters
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email

     # email:
        #recipients:
          #- moushab17@gmail.com
        #notify:
         # success: true
          #failure: false