
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - weathercodemagic
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Flutter Doctor
        script: |
          flutter doctor -v
      - name: Flutter Clean
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Test All Layers
        script: |
          flutter test --coverage test packages/open_meteo_api/test packages/weather_repository/test
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
      - name: Decode Google credentials
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Build the app
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          flutter packages pub get
          flutter build apk --release
      - name: Distribute app to firebase with gradle plugin
        script: |
          cd android && ./gradlew appDistributionUploadRelease
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - moushab17@gmail.com
        notify:
          success: true
          failure: false
#      firebase:
#        firebase_token: $FIREBASE_TOKEN
#        android:
#          app_id: 1:133119966084:android:95595c1ca11c02c57e7bd1
#          groups:
#            - Jamiil_Tech
#          artifact_type: 'apk' # Replace with 'aab' to only publish the Android app bundle
