
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    # ....
    environment:
      android_signing:
        - weathercodemagic
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Flutter Doctor
        script: |
          flutter doctor -v
      - name: Flutter Clean
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Test All Layers
        script: |
          flutter test --coverage test packages/open_meteo_api/test packages/weather_repository/test
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

